apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argo
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:MohanadAbugharbia/homelab.git
    path: argo-services/immich
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
