apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: immich-server
  name: immich-server
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
      - image: immich-server
        imagePullPolicy: IfNotPresent
        name: immich-server
        ports:
          - name: http
            containerPort: 2283
            protocol: TCP
        env:
          - name: DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: immich-db-cred
                key: host
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: immich-db-cred
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: immich-db-cred
                key: password
          - name: DB_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: immich-db-cred
                key: dbname
        envFrom:
          - configMapRef:
              name: immich-server-config
        volumeMounts:
          - mountPath: /data
            name: data
        livenessProbe:
          httpGet:
            path: /api/server/ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/server/ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/server/ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 30
        securityContext:
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-library
      securityContext:
        runAsNonRoot: true
