apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: immich-server
  newName: ghcr.io/immich-app/immich-server
  newTag: v2.7.5
- name: immich-ml
  newName: ghcr.io/immich-app/immich-machine-learning
  newTag: v2.7.5

resources:
  - encrypted-secrets.yaml
  - database.yaml
  - immich-pvc.yaml
  - immich-server-deployment.yaml
  - immich-server-service.yaml
  - immich-server-ingress.yaml
  - immich-ml-deployment.yaml
  - immich-ml-service.yaml


helmCharts:
- name: valkey
  repo: https://valkey.io/valkey-helm/
  version: 0.9.4
  releaseName: valkey
  namespace: immich
  valuesFile: valkey-values.yaml

configMapGenerator:
- name: immich-server-config
  literals:
    - IMMICH_MACHINE_LEARNING_URL=http://immich-ml:3003
    - REDIS_HOSTNAME=valkey
    - TZ=Europe/Berlin
