immich:
  persistence:
    library:
      existingClaim: immich-library
valkey:
  enabled: true
  persistence:
    data:
      enabled: true
      size: 2Gi
      type: persistentVolumeClaim
      storageClass: local-path
server:
  controllers:
    main:
      containers:
        main:
          env:
            DB_HOSTNAME:
              valueFrom:
                secretKeyRef:
                  name: immich-database-app
                  key: host
            DB_USERNAME:
              valueFrom:
                secretKeyRef:
                  name: immich-database-app
                  key: user
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-database-app
                  key: password
            DB_DATABASE_NAME:
              valueFrom:
                secretKeyRef:
                  name: immich-database-app
                  key: dbname
  ingress:
    main:
      hosts:
        - host: immich-test
          paths:
            - path: "/"
              service:
                identifier: main
      tls:
      - hosts:
        - immich-test
        secretName: immich-tls
machine-learning:
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: persistentVolumeClaim
      accessMode: ReadWriteMany
      storageClass: local-path