apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: deploy-confidence-database
spec:
  instances: 1

  storage:
    size: 3Gi
    storageClass: longhorn

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  managed:
    roles:
      - name: deploy_confidence
        ensure: present
        login: true
        superuser: false
        createdb: false
        passwordSecret:
          name: deploy-confidence-db-cred
  monitoring:
    enablePodMonitor: true
  switchoverDelay: 60

---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: deploy-confidence-database
spec:
  name: deploy_confidence
  owner: deploy_confidence
  cluster:
    name: deploy-confidence-database
