---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deploy-confidence-secret
  namespace: deploy-confidence
spec:
  encryptedData:
    DATABASE_URL: AgCo79NESfoYAHzS/8cVCLt1R/UG96GK0eNA+yewJxVbvPkxQZJw5JBcKogSh0zopkWfvYtUzs/KPhzn2qO5ufjU9v+ke29F1nCUmHsp19mmqk0evK4FSAaoAm/c/W051E64Id6q/de/fk9MFkmZ7tBLQwjLe89CzNDkgEzxm83KqD1L7ncNV8kjLC8nHCf3/B53nLe0hfnEBq8sitMD/S6ZJ20fBVrSVICme/FmZ8F9+5mluiMCyudANFH0KA4v/LFJ+6zGBK0tcGaA4KLKbT2Ui3P5slValEwwDxrWg4tBXzDQTunO5CpEUdk8jvGbdDiL/BgZH3FJpUDyH3TinIvTR+D/TqrJfT/1mlUFSZE6tWbWU3raWPCpq+kWSv4W02sXIGtorREWYkV+jx/KCUgRfE3mRWuhhRKEYGUQzrIL0tr0+gJ37FVHwtPLeBdhFp3eIi9RT5YUCwqEopxdHhWuxBa1SO/1iM4uJr2/C2bcITYEfLiOtXXUoTsUlEdzau6iMkS1wRlcHSJbI6L336VhZOFvLrHQw/o2xD7PZHYMXzdZFs0rcLRob6MO9hL52H0mXjbZ/o4O+oPkxzhXclHP6ZkuLue4dm50BjlZKBv7p8u6Q6/DKaTdMJW94D0N1nCugahuKFB/yGm9yBIuXeDPykAbFGIrDAWdyIJNB4qLh9v3SDK8IuHc4KribNvPfmO/VL7aY3SBfQN1vpowkgNQr8YGLIc7DsRS669Y8lqLx//0UWLVgQd+E4CIaysccUoD+E7HFAeXR++JCgFX8ml/0Q0rfUhr1Ljy/4iW9oUpYu1yZ2JhoCh6N3hm/vSA4f+2dGes5vULUpg+36NeW1jSt6xfidcz7RXohLCwnNkd5JtTrr5DWAFjZzrW19FYsZE=
  template:
    metadata:
      name: deploy-confidence-secret
      namespace: deploy-confidence
