apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deploy-confidence

images:
- name: deploy-confidence-service
  newName: ghcr.io/anselem-okeke/deploy-confidence-service
  newTag: latest

resources:
  - encrypted_secrets.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
- name: deploy-confidence-config
  literals:
    - APP_NAME="deploy-confidence-service"
    - APP_VERSION="0.1.0"
    - APP_ENV="production"
    - LOG_LEVEL="INFO"
    - API_HOST="0.0.0.0"
    - API_PORT="8000"
    - PROMETHEUS_URL="http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
    - CHECK_INTERVAL_SECONDS="120"
    - DEPLOY_THRESHOLD="70"
    - KUBERNETES_IN_CLUSTER="true"
