apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: longhorn
  repo: https://charts.longhorn.io
  version: 1.11.1
  releaseName: longhorn
  namespace: longhorn-system
  valuesFile: "prod-values.yaml"
  includeCRDs: true

patches:
# Patch service accounts and permissions to add argocd sync-wave -1 to ensure they are created before any other resources that depend on them.
- target:
    kind: ClusterRole
  patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "-3"
- target:
    kind: ServiceAccount
  patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "-2"
- target:
    kind: ClusterRoleBinding
  patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "-1"
