apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argo
spec:
  destination:
    namespace: ntfy
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:MohanadAbugharbia/homelab.git
    path: argo-services/ntfy
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
