---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-db-cred
  namespace: shared
spec:
  encryptedData:
    password: AgAGoNXrqV/rYMM1pQ8byEmk9Pxez96SOwvqArnU+2ASfaMPAyCxFn3HM5rnudAR0tmtEouGzC5Fow92cfWpOUaVJBKuTKdzKN3+0P3Pn/yBpYACz8rZ/SmzDLNB0IW5hwoDMrcUmXiAzgIX34omfL384rnlpkhEdepOYtGvEzNzFvPkhnHfSd3W0bqMXBPlDP2yd2O2ngYmWXLwWadlVLiC/kRg3Nt8r7RfpNbDpZmJwoL+FomGBAj4RfERlaHubRjxFwAR+iaUa/UEzcm5r+9kajDe2vp+JcOw1gSqMlR5fuGVrYqsnwcWCkI/ijhPDLbc+1+AeT//QNPc1R3FxJ/+uG5Vn65B/IiQKaMzSinYSB3owG9F8nx2hvaRCtcmy8YLFs8iKxFw2xyq+FqN1+fC5IDfvlas5VSIpoH2gXECijLdXzIL8D62NHXaU59bQsQB5DamAlV5VQlsEEysVnD8puNsWPCeE7Bd0/juiluOHf/ztx/TUpgDA/kkndT3XXHcV2eIppET/zdYpdmeE6PpeO7nrUmf37KNVtKpPZNvJbTGatZCyBhSHQSx1FYLWdRGw960qpyVI+5jJrJWe9+2/jyaLgVAAu4KY4B741KxLwFjdRxAbHS5HW6YAL3COLqQHfD1wkwxkM53IeqXTI2TGywRY+NgKimzflpTHovk8uzpJkUtLIPBF0A03ZHnDezQfH5hNmtxOtPtZVUs7QGICTOMAzeh+HamLcFo3fMkoGmYtGU7tfltl9eGGg==
    username: AgBExrylmeZNxiubIiIhK66NktqUX5w0pfRWdr2PaOt3kDJR4vcNdj3sM5wgDTc18h6bid+p8DeH4t9YXvttvVkA4UnPIz+KPY7IJpTHBU8YGNxeiShalwOjMbMA+w3SfnmhTJA2hde6oMkvXGAoU4g/T6i7COBJcJY8rt5uy/SV7CHOXwhHm8xYmuPl/N4hRO+9guhZKt9LwLPDpO5O/p9J/xcvzHqEibH0hgRqXIODRN126TOHBHazEvXZmN91Kizkbin5VjINjzE3vHkuiQf9+GvmKDcdETIwmhmwlWeHsWOnFqz9xv21efFwovqUSgyojX/G8nMqaeJcQP6zg8BS8VsmV8KvnmL6+21H6N4V2ax09YKt6/nRxR4eaGPVCUUuNTIaNqK1uu6ZwmyHK33KSrlxShXwXZPouL78g/Vs/A54bvf58AylbPO1D4K6zq2J1VpgO5bivzzlYnd8DriKS0/iEe+ASNzmZWRw+OxLX1iqDJvy7uI7Eb6Hxdziu8avM3KAsUTtsKRog4zQs8zkSnUU0dUHZnsR0ZHnn+rfxQ4qFDrmw4NyrWM8aSjQAEp/IiA3DtdpwW3A7TtbxFEBHlv2WBLvSX0BjgU9UnzJooNWctv3Mp7/Otk7xBOhPRkJYv7FwwYsTyis9TxIQ+od6i49I4WX3zF0C4pOYgL4ywWezOZL0HbpwGzGMehXSLMhkF4TUBI/HiI=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: nextcloud-db-cred
      namespace: shared
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deploy-confidence-db-cred
  namespace: shared
spec:
  encryptedData:
    password: AgCA7CxM9X4r+Sd0Lkblj+0HlQK8k8ux0si0Wi9o644YjY/ezMFIke9iU+fRCU9DnXuNF8ved+FBoNEop77U68OAPdWkq6B1lN8mmtFDE82bdzp7+BZ0thx9eqaGxIl8r9FxNDcPzIscidwVO/ANMKZ8yP9WbzKibU01zsplM2HlRBpjbJXRa911biN7YOwem2mN811LLJiyGZlzJl0BWS9D5EtYx/d1zkM0CYf8I7Ya+OroeJzrvKGaAfvn8zh6MGcrADPcc/wC9OIo/OENV+Gl0OJ1cuiHAYQYR9BmXFoNLafP+aVWOtuk5FZDdCI2eYS/itDCJ0Th0CZDdY7wvHdMHmb1+GNS/pjCfoaT6gDrhj/TYmijdasgTYQeBKgkD87MFg3dgCwHwQPWbNSWsxyZPWb+qvVXA0MnuVHQdGdeDxLQ+q/kq92rnOVtDaYXiFxcACComJYP5BfOjnH3OJNUpr1g82ujNFt8kPMlbckP3v73oHHR7u4x6R6hLymYOl8ufELxiAnIjyoBgYf2Mz5+ybGoVRp+cqfb86pUOlV2AYQ7DTFaIMUZa8fwhb64lRNjU3eG4vKtkDMKvFoXyybB4qx7Qba9c7IgbawuvJA3CZhMmS/qexaQ9I7Zguobp/mr0WmfyU8q9jE8r7RXRykeo9HgweKXCjoCeOOTQkjdwpRYQKwBkkjykstMpQGT5eMTlCQzmPuI3zJmCFSkCAHLnrMN6ykpQu6aPqLxtHm3a7O9mDsLhpsVsBUNeA==
    username: AgBhByGo3mUxUl/CieSTXN/W5ecqCTYDRuVz/G3dsPo9qRhODL9QGJINVIoGEH64VUdLzBk6SzGWpIQ59Iy6sJmzt+hXS64RxfKXQCbmxFcWxRMG2WhryW++CSlHZeJ8ROK/uxY73rfoQ+cg83ahV5nQQ9wC9H/DQu3omT0Ca4ensuMZuU8SIiGWli96XN/pzE9Aj2puUfbJnVXPbCHyz78RWCru2UCYuOeBZ2dSIirLfrZTx4bKW/yrWhpSwzjXzEwRs0b6iOcOQYLvBPVNkC+H3rpf4hfQwsR05rg0CEnKQwEYtrDXjfMIKHI5EnQIC9tUjolO6QBtgdiSiz1nJC7cqEZlp5FqpJ9RjT0P9I5teToR9hypgrbeqB/TWihTJiUzDRNWnJwzNDQF7iBWIKSIXzh1PmZOAbv6UvCOacEgCu0h/f61L1Tr+4WjSxDl+lbDDL+/eX7AGqLOjVaP0BMl3t5+jUTZ89TSu3j2owIwOUNxaYkN17yFOrmrgAlSfEoxfMkRblgIn4ySyB3Nz2MhrE6cJFSWDrIDUjlOyAKQsPdrLQ4UrwGtqcT2vSyesdXM2VOQqkwjdZ4gP+QyF0fUJ+jRCyzpU08/IAVcRhfdDtUAI9Z/gdTWTSEg5TOjGPhmWM2JwsooVDdwAyfBKlMplYpK0rRac58pAt57cKWEergHvqLFm3VSnx29QKVFWvtNc/b1uqdoiZo56XwiSKP1KQ==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: deploy-confidence-db-cred
      namespace: shared
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pal-odoo-db-cred
  namespace: shared
spec:
  encryptedData:
    password: AgATen94eCByC3OP2rUqD6To9+BposcLZST7dcKDd0CMApnBjn9Tz7J/4eQ9cGce4/TsDKd9fKBymWjZI5G+oYyTnjo8Vh5ThqVSgaN3dbiiXE1JKRlwpyb8j4o6hKr+XecJ34aAO7jipxvouVjBXVEJgAFJTeyYpO5aRa3nVREK1EkYCVJ/4nDCRG1Sq8ps8+6hQQx/s4pxtleKne+3qYfTsWnsTAY8uZ+IhphbwS+iKAIhaPNbyFZf/8R0oKb+9MeqeYiqEW5GWC1pAtek9uDsWlXTPMrwDMbt5t7pL4qefTdQjabZVTi+LzkYWCwt2zhG+TIU/fOLagMWJDtXCwW8AWor5sl2BDcgWA7apoQD+vS0xYrngXQX/53PkRDsGBvUrYzAbXcIftLBITYPnzSjgbXTUJaNRSkUHPZqF31jOirvdsW8K/yTn0EKjkoI/IuooX+53Nz8SD4knWlQ9LBoh5mw7cFZJncFSvGh88v2d97oP6M9kUSnSz8itnR2S9SlyGxr5uj5G7dOeoejtKW8BKd762Ro20pPGhYgA+IHQMi02bhu9YdaTkNvtVc8u8MreoepSVGrR+jwHKXWWe9wjFoTcjVOiIXZXAAYo10sZDmsRdQJvbX8vkVgVqlNvRc56ELZL10OaHJ4G+ez0rx6BSJcRaxMb+gChNnJ+iiRv3oKfd3IotL6CVdmxDY6GLOCeuef3eU4n08jEnt8xUys3ozvrH11TjWa+vARs08Llsi/1x1/A6HQefuwjQ==
    username: AgAxhsyF+6sdHRCBjZcTiAME4gcBtXDHKNv52Dv+5IC+rYnypbe9AhZuAX+rM5z/TizXKTval9BMNtJ/2SiKzX7cT8o6cwUmyg9lb49xhjG42lCa2jIZLlBb9JAaa76D0DzbCtFOnbWxZ5kZQoK32E5X1cKjzpRT6U4N2W7lQo9NbfTR790zULh7m9rGFDJPg8KFKLCzSa0/NyrDnco/Y+nWO6TKq+cmBSENJw3XRPivcb/BJs5kKEmu/dgVuAQ0p1QEW+h1I7xFh2mYby2yfHloQPZzxr7atAaqtF+D4EL5yS8c9hds1KWd8L39gOOymPHTO2c1rECjab2VGOrd5F09INlodFWPUhquW18NRCbfK61iodRwuP008i3aOnI76Th8dPPkyC25WpdDcoI+YDeKFvU1QY54cvGaQ/EJirQltFUnoqZp0uVCvaeYvX8erB/tyH+00Jn3BiSEeSRS1G4C0Mo8clCRf+Wk6S8XayiR4xLEnz4HfvawNseTn5bU+Jfq5PjXiMhdmapuX8gMCRqtTjgOlqnx6lB40db581Y4SlYXri1hcf/XJ+m8ZVr9a0zstqRu/3LK4/vQaDc4nRVZWWamkpE1msIjfeI81VzP3R7TIPNeClzNLAXJJGEAdAEynxFO5wJ4CveignN+HaTbnjSC6fxbCcGwvz37ycdG9/zRGMU8DrUfPubFrSeJEGdVUys3LEfHIA==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: pal-odoo-db-cred
      namespace: shared
