---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-db-cred
  namespace: shared
spec:
  encryptedData:
    password: AgATcNFHOl9Neu2U+oOruZOJDzrfXK4mLiwNUgnAziZcj/ceUM0AXX+OR/pvwyndRIC5Oi/oxJEnp17eU9GpdIvaM0VwRKI5Gj1u/8rUPZro+aB+rc/xZaW6qudFWg3UVhCvOdDq4jL1Ft/pStMepusjg9JSRDRl6nAIpufnco+MiYtsJPLlk6vHaDZXmwYd/jj2XS8IGEWmlNi+ctzcJl2SotdrmclQcMTDELHwEsrPS/lmWmwaJkUTjrknb7s47pZr0xWqStmmaOH3PLMfAkbaWgigO5ZWp1aG0M1Zxd2LVWF7Z5p1hmb3BdZGmsV/kZHn5bVK1kWKCkYZsWiHbzwevrNRD6ljQL7LaZ7WL7HLHqOdCaGjtrQqubA15ElJS2U2GhfuqTnfMlnOHaPzR6jyD3s8BvabFci8e3v+5QRLm6Hh7ngEXmTfgtnUuSnUMTIZ2bBvmEgthX3Y8wNp1Xy9vxfKew4c0LQhFbvUVV+zIC03/XK48RyT9M5PlWZWuBbMI413Vs6dBGmu5Vd7HcRkjiRsECQ9q53IJ4in2mPwnoEiOEXYbSy/vedni9QUqQt5DEYqQ3yMimd7eczmkMe4dCYGAcoqUL82iBaNl7qIBFUoOf8jP1mCvtzUFl+ZniAnbfOAHlBhYOMo2pqgmR0mSv00ErdlB8+NkCH75xDmEVYCEt/4gqNv7TWEyOVr5dkAMtQoxsftEIQmC3mMVWYFyjQmJKYWvoVl8ZsESgFJC/NGFerINenuKb6sRQ==
    username: AgAyembvUGwKAXpLSGaMkxDcddaM2YxCMgjLxwyB3SWe+jW/tUpfUzvYSEi5wKSTxZroyeEeVAgNUorGPHOs5HJsQMzJCcnbraqjkVPKjd9XOZ+WTCbqwJDIRrJvxL/0YQEmIf0dJG9JcTKjnikRnXjEm1XuWbhXro6TmNfXxyA7SS+6iaPLpT++woh+CtDqex/Juf1JpBZt8XdKe0tHQQhi0E3gGeK603Ld8ZYDXscpW0cFREIvpLCmEUj6/ngSFbA1vkxqDI4CV9NbxXufoZ7QHc75NK/Po9kIYNYsenV0EbHqsYge7Hh4u7uiMPuKe1Xb93BLGAiL1X/6tUaTRsAHjyCMr7RLF5dDCg85XOGwZueS46B9FP9qxoDYAk+CBQFJXhEi5hdZrLn8aCqNiDyF/PnsdDQ6cvYXvNV1XA1Y4Tce+hGuWBdbvPM6DzHTRz3gnHlwyRUTOP6dVWlOIe2ciH/mqZch0+1apy7JW1BDKOWc18lvyjNvMUpxphVQsj/8nHR6uEzouy1t6/0DU0e3kZU6glPRoKpHG34NBHBwaS46zGNT0XpCV8DV5PV2+twLv9GE2Iel+L8JF+1tC6s9JygUwaxtR8s/3s9KnJHnsCDZHmFe8eW8O8S/6+6d+1s0S5e15VjWA+xf8ctXyGYi5e++t1fF8CSVp8NaoVVUZNOdDFL+4PEACA5FXFocgo2FM9USDIbO8fY=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: nextcloud-db-cred
      namespace: shared
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deploy-confidence-db-cred
  namespace: shared
spec:
  encryptedData:
    password: AgCSa+uy9szi1g4LvID+V4FRnlD6C7civ5EDoJKTfbL5JK6JsRbYmSe+AVb1oL3m1dtEp+hHUmufWK4ud6BPlPonL4ADgTsnDXi5H5I/vDKHbLPSOwPsfoqAJPJRAqKDMCSX88133sVLb7L8+9+yXu/39C3H75+JGlqTdJe8+HGvsJNc8Xcy6R6XrTyjOz1KSfUA0wl8uK8OBRfUofXC+J331SgxWxynma4z8gwuAU8pUuOpzIfYft8FxioZJgSVUQVf2/H1BvVoXDqK/gp4q8Kua6xmGopQDSp0s2GLjbJXHvMtfO0va9mAnx4/0+G3WGusLpUriGnS04AXPVMRp0k3vgcky4cyTKAXNR+HtlH9kG+i3u/Zx2rDTMmP6ymq0EhLe4G1s4En1cfC5jAJNsnXJ/9bi7rmfpz2k4iVYSQZ3LQlJEhpBl/RsqNt5nJtuWPO0zVIUJnHOiyq62E+8uIzXHUDS9RGIK5nSbdtO3AGGbKL4gEa+Q8UrPEhlT7z8nZbrCU8b4XjshopMwQjHk/PtJ+jbxirsgeoLE/TKG9fXk9YpyRxM3ag2y6+lBSyWk9+e/bco5JFgOOwQ9aTr90X3H4TxFjEn0ADXCOsqQViEJtycyvp5Ik/rsxKDmd0OW//KAVx8cCdSjgIquTzZW+U8jfMHQejGqgnhIU+N/neFGbwp52XIUjKRGRKyY5KNuKcC+2I6hzH6Ih5lUm7b6g0mXzUTWGdH1kdqq5sWQkCb53mwfRr5XpRuhAbjw==
    username: AgARzMnFNymYQ0494TPgPtsdk3bQgUlnRaEX1h2AmvqVJupQKv08H6YUjmFvOrURvxCEYsLCmkdcFUJZmPxEDNJMb5UNWfHc6AHCkt7A7OzZC1Y4BddE+PgiObOk5UDcUCGVD8z+r1VBIT573tzQNH5HC3HR3qvthM9tCv9SVpqXBvlDcHdZJl8D32D1h8tQxgrizSTeTPeX1XY/NHjcZIiKGdLiOdUuDyK3cD/BTm8p8iE+VRStpJx3vUHFn8buwWWLIMnOT9HjHddr2D5F/sLqjwGvtPhEve3CZzhVRkPwR2tXYn4zEX/P/FsWqIeNvG5QIPZKJ6Yv/a3Z6oHSgN35uaSOYyEjjFYMUvqud+oOXEtVIpstdrjagVFj2NTkrKVE9s8AAdjsIL94/f6CvAZ/pl570E4P64Nojrqjrmifh530vn/DyvMPsejRZu7MBzXgS1gHowPLAs1H+gQSr+SswaXK5nbyDeeJrHXA3E2uNogjvjEK/MA86ydPjLn8dBgKPi4czfr3ZQno89i6//GlYgbUv9MPneW9pQ90CtjovUpu5YgKRJRsnOiOzkTzVG5bHOXQmEjk1dpCewoJwdndHsq7Hww+jZZumVLIe9Q9kC55KnzHL3oumAODgHfN8rAEsY3o3yizq0gWrM0rKAKN80hNF0CqF4VO8suah7Z2QB3iYWakW3OC1z4+b2wex/EMnBGha3ztAxD8IsfpkgZweQ==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: deploy-confidence-db-cred
      namespace: shared
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pal-odoo-db-cred
  namespace: shared
spec:
  encryptedData:
    password: AgCUcMIx+OBMAFeLSWnJnAXCcNkuj8sFFCsISx0eSToaYJdUsRntsjlqftwKFv4Wm8DkL6YQ/kFKvS7DBPayD+ksxecsgU3ku0OBBPUxLMX2+isVcHxgU2lDcE/GAj6bMfXWsEYQKSG/Bc78tSfRZouUn69bxq450WmNzo9D7NPbsEvcm3TfIifa7ndBF+nuU946iKP4YpYk7TQDphrWphjRftVFYIzFuNMULkn/WgPpuoK66fDpF4zGjWfD6E/D0xtcsZl1GPJMyvW8vU+LxcIBIjZKNDs88jDZJUwrAAAF2D7o8ndqJuf4uNXhiepCm/9vvIxmIGvRi9kyedgJbAN9mikCG0JedmE/hn0vnVboks7YtwfysvUXHWgm98k0boq5BamEUAaazsdblBGtAmQdtefSop8o7t+lycI90Ly2A6BJ8h2V85NQpLFSa77M2b8Be5ibWu8/WzLlvFugDQY3k1wosgDBLOA1vD9hW+oly+x5HysLGBvGVcxFOwexZ8Vm3DF25ukU3LHOWWpPOVLPdkhtiUqdSSuuruNfXYNWuBUIgIIqJqOfapqjd4uhc42svBDTMNeQYkyibeIwaDGg9kIWAK4a+ybuc6Iv0Ehb71kfhDxMOq6DldxjCYmYPi3+FgDw7nFdIx315R27UtwtIfw+Y6ZPjpzEFFTU9dfBjfeuMtPUYstbWhLFViRaaqQ8oAH+/FHWaRsPo9eeCDkYjOcHcyXihTL/TQfG/d1TLW5Vfa1/8Gms852b
    username: AgAPaJ8KsMQRjS8NNboX0rn9rvZBy+ghfYCXD2M6ljBTEhjLGiVxQ1JITiJyjAL5FFMEdyeco09sg2hkT3+vbAJY3Y9aQ0asQQwq7Fh3BtdHTcOFlWFST+gH0aGSqA+jeOvcujirLVbbXLE3XhlZa2f9CWrwjlVLjpeqOCq/nFeerV8agEgGDi/dGCzGCjTcL//U0hAqAkgSPx6zALcxna+tTi8lUr+WFaSLbrL5E5N7oLZ9dNDbPQGLmZSxlqqwsif3yaWUqsyIFXnw6aTiWnJYtKevXyibEAI5c9Sg6HrfzblXqsRW37eB167FXJphupeMQAVBkC3JjLptm4v/SYDF2RYSt/qUUSBz5mDcJNZaB+QoD99CD/xAL0zXV5+lWA0BWewRS5t/n5HBTEqMTt1kCtxCyfFNOMQpF2XmvN4GzYHs2C/sepBc/8cIB4Q7ETqhCx6OrdlFdPr1XTbd8zSeqKAn7f8uSPwFIhKpWuFEZ41ZG5YlKqaowyL0SXvhETE3og37f2/MJ4sJRogiyFYZiD9j2ZjTAAsiB+ouj+VkH04VqwT77BG2cfrIdw5Chs5avNRhhR4F1c4uvdXRItxcR7aOssE2ybChnI3JNhIyW+hm1yzS9SxNezBmzCm4zEX4Smwq/IYSwZIukvowk/5npX+98nqKu1SitFdxONpwjSTjZA7pVfJ6mrAmij/dlLrgtp9ZkJDuIw==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: pal-odoo-db-cred
      namespace: shared
