apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shared-pg-17
spec:
  instances: 1

  storage:
    size: 3Gi
    storageClass: longhorn

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  managed:
    roles:
      - name: pal_odoo
        ensure: present
        login: true
        superuser: false
        createdb: true
        passwordSecret:
          name: pal-odoo-db-cred

  monitoring:
    enablePodMonitor: true
  switchoverDelay: 60
