---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pal-odoo-db-cred
  namespace: ababiel-preview
spec:
  encryptedData:
    password: AgBBrTyJu5RW1q4cSBAqSelA8mGIcL8Mz2G2acqgEsiaVSsOdungFj4PS3tMr/yPKQ+tFMA4dIfZclVT9ruNHmIP4K/zItoOk0t7P6QsuLjWkPAc0ngZrVWUH8VXAoHGcIzTvWYih9PqBVpMtSGWVAS4zHszZnPMz5aUnq2IWBnMtuo8lrF6QxzY6NSs3RYkUGWQ/UlNBm44JMMg34dcmabrIgv8Rb8sBAmnB8YC7hUugwde9ggVwgBwRzdCPRgUwLADdu14uAyqjr5uEjW4nnnm7bRL5CrlqQqifmk/AbVA5QZiZXSMv/UoCd/L2Ci+SwnJwcRwjcWNQ+zeNVm8Hm76pbwz7Udn6oB2b0632KM6n59LY3SDGQ9S2wuVlH53SY2heC0O4AZu62vAiUitz1kxQyFxDO6fOzabDHgabqE5vGP1SRSWlXOWHPpZv/Zb4vJQ3mlfZjZtsYOzKCea3zV3qRy6Ke3xB7/sCUjFR6j61sKXJQvlxbn9l3emdX/Hz98ZWGkK07FkCZGIRZ7CaQ6i75Kk8yPfVcJedsswsSJzofk8RPOIRK1PG+yhNgZ8RI+QhnF82p7SCe7SyKHeYrmxkU8Jsr7pLHJ7VwvaE1HJkQSmwKz3fpSurcCQoYETEEdw2fHXYE/uTdkyTdRQ2PNoVGUXSe31VlGciVYV/2SnCtuthG4W37NAXr2nOvswF3IKVBKjKzJpjjm9ZsUFsPT7hL1dVmbZTp6tuIdtsfuOUcrw+cHD+R5MidiZ
    username: AgBFaIgUIy6PrFsrzWItwrT16LR1JOOt2q8WhiAxIDWfHAZgyfwrwuZ2YVFwp6ZAJDYuRepkhEJ5mxRFgTAbfYh1iI48tO5h4L9zGBmG+Ny3DEaTTxVZ37sNF08ISsGVDHwE5EGNVec9AjzfN1Wl8ODXNJqNBAiyD126XuLNr+6GcgluoOg92v+g9hl6NjtJWJeNNZIqOEQXjJz5S2/bv/zcrDgOEUw+bemYaL0GNF9CVf5UIB+Dff6un9GKoU/61b6yLXnULoASEupFQCj6bBDdGgccIXqo+/iJ4lzpGVCDsf7rKNjs9sclG1NQuRRtCnlFF+RevUZCPrMY+m7/vE1XIyqcwhqy24wPRhni70Njmt4UUfDDcvpAjvWj7KLGi3uK/ip92cEik0bl9PuIN+jnA0o+Fon/qkkNldH53qGHcNJBhUCbKpb4HC7un1y/zlV2qIV1pkGhfFypLTuQ0K/25vb4CVgDd8MI2Sc+jzi5ARux0e+WRRLbandY14D/keOBNFtsDZLHLUblXP5m1SQdMjnbjFjPzIriS7I+1jt0e+Rz2Ov8xLIQTbjasDEXeBgco8fpLezcen+4PoEVl7MCay2pv3je70T5Px44FMSQ/CzVpdTKWIC63Fnxn11ObjEYEvPDnXB7R8sgCMMY2NaD6DTpMOu1huzwrRylLka+nkgF0u14KmusiMAAc6ap1WmV7+Mprx/Aag==
  template:
    metadata:
      name: pal-odoo-db-cred
      namespace: ababiel-preview
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: ababiel-preview
spec:
  encryptedData:
    .dockerconfigjson: AgAMGlrLf5eoyHL7lz4aFq+zcsfiIK7GsTO/odPpHVZp1Tf+LsBOQtvPHgAStTwxWTq7Nrkv5h/QOqZunyp6oPv38tm6ZLuJuRqu6ZmHbPzsPFkAUdGWr4+fyEAkfBlcEqwq/Nhn/V/wx5sEQUQandfaaPM2jTOIruu5+nuJk85+cscCSquGVwXdgC0MT99rAqvyH8ckQG5+c0VJ0BUKtACxyQ+hQxlRCmpNBtGdRbv59cyhc/GBBr98wEQp1ZOZzdu8+rFnpH5zs6B0YsVS12ChOy7rnvC7FO2C5DF/dcmDDW6Rm9tmbXIynEX4fQChUzdSRGBe+gX5Va5//AxM1kqgQzIMvuxEWPWeIHzLaNSOsTPbG07+hHyZ6cB9CySfioJRjNG0F+msMCDzR76jM0MKHSYkJ4q1xuNWBo7yxCRXUzCOZh7BORdxWy/lUTAbetIIsmwbc8OlDkys9I/laHYl9H1blA+2VrVzxCMS+FfvhXVM5i5MrjzRSY+X0MhY0Ek5zrCXXK7DwELd5lcmtoSXtnrGvQSGXSiX+xDj+UmVqU7EUcMnTAkp3Qtlc6gxG5BMgZYq8/TLe4SxevQiYxJhYDFnbULys1CTHKcb9/5CIHNlQ9ljYruQJpJcVB+7rBHeuM/9RNX+8bAGkF+PB2gh3DYcffuHNYwKp0uqk+U8S+FPWU4+n42g4cgnoNKnWOLXLW1nEo1iPDCbYo6nN9v3JZTqdDocWI9/n1ey5FapinVMfL00Clnku2jgyUCUvc+OYHy+yXdorYJ7d+59jUi6UYCTO9l9aJLGt/8uL4+R2nwqmYf3BciEK5wZGXGJJlyuSdqBlYtcnVsk5oqyRG6NkYZWDrF1XEmxH6GrZD+SkOrvF5YrwQbudZScSN3BDc+z7HXvin+bqIZ61Vy1zOnt/XFERyJKUMwtXiN5RgSGPOCa5J3GSE1iXQHSHq76II/DV4Gn9Mv43zS42iPLMILR8Wo3M/V2SGqKFpgEgqwQ1I3XnU0=
  template:
    metadata:
      name: ghcr-pull
      namespace: ababiel-preview
    type: kubernetes.io/dockerconfigjson
