---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pal-odoo-db-cred
  namespace: ababiel-preview
spec:
  encryptedData:
    password: AgCV8SEXmrU5nfo1AkWF8ZHkBHXx7SqlGPAvNnJFCo4v9ftewYG/LMYkl43KF5dT5hl4XSCjVjsHlYNMBk1usa2KeWBr9f29dL3KUAUTJ9XJSGdWLgyZrZB7TK+UNVRgTXA0gjZReWfp8NpEcw56Y+BMGwq95VxkXqcH/dvYptyh6ea+/CJiL7ZukT+OWCIHOey5tYZ7sW3p5avXRpXFWUe2zHTx3KaEkJnLPWRjUZPsdhu9FvWhTd9IgsKQy3THJY9r6qqDbMo2vIsiOTtLNRfGyeHBwtskn6xq76sAZvickcRg/5ScBWqYKgp5SBciX/j+W81RiMit3OJ3NE7IG4d6g4L9qrktVkxUKMujZTzrGRHqrY2HJNM/eg47yLtOJXOC/33e1ZL/oGiSbSXXm1FfbUYiwQRbMvAmxS5Nq3QWdBuH+VAt3gly9Jba7bCdh76zJynUYotQIIcmovonr8K/fQqQJfdur1d45iO0Xt0Dy0BuzjeixpTlHD3yZNABZjv7H59vpvFwnMpaTkifnB4Y/YyYd1Q82d4eqDPDu0nnAIp2SnOQeHWhcZzTv0OVPkc3FEsSFURquL+SfSo5dv1fYIDZ4KabAMIi0mwVOFjjlSakekjrlVEdOdgKUwiIvgmUBx9AyFJrRo5QUcYgBMnzCIOWWinSyL8DZxA+pt7H8BYlFgAhuxhVVDRsbHu9BdKQ+L7z6JiynCyFukEPt6SAhM11EFdwfrpazTeC7u3yAPk12rjw0C1AAQkibw==
    username: AgCE8CtxNGQrPnJ+ubzxM3HNikGMKnNpthkKO37EvwE3W6QpEl73lP6naCtcxFSOHDXs1LQqbjIBuf9tepCMhlEfq/i3GMTfuoYjS/uvUUMH3fvj93tV4cCwr7qKldusqIkecr2Kn6N8ShGJgtBDfg6nNB2WClhxnaArG1md4ZohJnut+ZO/hpw6aIsjhKNoCulIJxHL0u2k+LyXLU3/jRbPx0vseP41mJkZni+G5YODisnnxs/XvoP3UNvi2Su/5Gr9QFbIh0XKJf3CQGZ/AwVHZd3CzPY+j5Je9CXcFQR4H11WOlb002WQW5Iyo63CV9gK93tIlmbNTO1e1VR7XFOabPxp/4bI1hCiHsLG555NEik41fO/HpOti9bAIayNHWGeiyzGfvmrJhShsUBVM6kv/lV9Ag5SQb7u7cN4mKWZIfFSkAv9z5xVAgxkwEJjGfbZLp1K7VyWH6LC3hfXr7M4G1q2Wv532/7KHgM6ddvPxxpCQiG/zdPqlmDZSW578mSqT9pqWiWcXdSBcOTDhikpQKbHThFma9cF/VOjdqcagiC/IxiYKfDZakx+AphXwJ9f6WUU1+kGtJIOm1YXHmL4uKhBne10iO5+1IV+g9Yj5P3ejx4vck1OaZs44K8MI836XwecpPq3nd5QOIbF+g+8y2zV9nPHQ+qQi1okQBr1VdgZBaaXCnDViZAki5nAwwbFpYx8vhugCno=
  template:
    metadata:
      name: pal-odoo-db-cred
      namespace: ababiel-preview
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: ababiel-preview
spec:
  encryptedData:
    .dockerconfigjson: AgBjm/p2o2LAL870z1t5aqpstu4RDQiRAPd+wUs9QznTvJpEBcHuBUytoaf2blnCNrkqwrRFQhY6rj2L3aOgPkcawTWwK8h6NukKB8KjAjLB4NTh9R82eBanDYPGzwwSxneHohIy91jG+KX3xSeKalQ+8EyGBbzMRIQJU9HA7SdP4qGPFGeydaOtDiaJEBBHAR/XmIdp8oW0Cx6Eo+InGe5whqjcj2ek1QGnB/69xldJrOQI/lU352Q2RAX0Nlpw6Cx6o4nn7Zicj7qoh987KgbbU/Jkn3wLTaQ2muVOdIUIswaF19zPsP/Z3GqnpEsCFBWsFy2hQglMdsnUBDjLFz4C7E5ylIS/R8KUrLOPoQyQKhDACzz1nNfnT8QEn45zTKVycohkOp6b5b11mEmGuEPXaGuo/szEXaKKPNweIqJMO1aPu5ie7TvJ+fjIz6RNHV9jSQ5PbVSlJjOdG+55GjKQMlgBqFoLmVsyOfFmuiFb5MYeF2TuLYjOoIeDw03gcl8k9ySKpkoIod/mH/bLOz7INNxfAPA/tY7QaTNFrN5MvORS9fMqP+8M+0jaBJCjI/nB0F8II/RpMshvZsK1iDmLJmRfT/EwxSPx3bvC4kftbAnUHssX09xAvTu3M2i+rgo7cp96XDS6Pg/WtcnPWYYb1lZGJVmzKU70lHN6LTFhwwn3/DU7XME0vRmGD/NT5tUx7CdYba4W0ZlNL+a2VqqryCca6I28LE17yek8CmO837xKj1+n7z0fr1g5zboFytve1tMyOHJCxvgni5oYgshHcoUJdg+RP3UjakoMmYGytMAE8gKWMi3ir1RO5ha0swIRYKOAYwEHsXejLF1oqW5tIwUvUBjm0fRj3i2Ph8+OmFYPH8fBh8+tClqV1ABb/MKlZeSuBoubFf+G7ZsTpb0w6giv1TkcwxF0uhlVCSmZbR2diIQAN8DmhnWqsMhVCNkMpYaS2CDFh5MuQ8AlsOFfPoEBAiy9VlGboddrxD7ilXdxNuU=
  template:
    metadata:
      name: ghcr-pull
      namespace: ababiel-preview
    type: kubernetes.io/dockerconfigjson
