ingress:
  enabled: true
  className: tailscale
  tls:
    - hosts:
        - nextcloud.tailc5dc8e.ts.net
      secretName: nextcloud-tls

phpClientHttpsFix:
  enabled: true
  protocol: https

nextcloud:
  host: nextcloud.tailc5dc8e.ts.net
  existingSecret:
    enabled: true
    secretName: nextcloud-credentials
    usernameKey: username
    passwordKey: password

persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 1Gi
  storageClass: longhorn
  nextcloudData:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteMany
    size: 5Gi

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: shared-pg.shared.svc.cluster.local:5432
  database: nextcloud
  existingSecret:
    enabled: true
    secretName: nextcloud-db-cred
    usernameKey: username
    passwordKey: password

cronjob:
  enabled: true
  type: cronjob
  cronjob:
    securityContext:
      runAsUser: 33
      runAsGroup: 33
      runAsNonRoot: true
      readOnlyRootFilesystem: true

metrics:
  enabled: false

prometheus:
  serviceMonitor:
    enabled: false


livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: false
