apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argo
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    repoURL: git@github.com:MohanadAbugharbia/homelab.git
    path: argo-services/sealed-secrets
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
