apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argo
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    repoURL: git@github.com:MohanadAbugharbia/homelab.git
    path: argo-services/cnpg
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
