---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-user
  namespace: monitoring
spec:
  encryptedData:
    password: AgBm0V3+clIuIgHCvZzS91E8m75RJZonrpzttFKFlRQPqccQcjuoJbySmA9mZP/xmg+H7U+Co+7xwjUC9cRTpmeOEEnSlCur/JJNUSE0eYyzmTiYgiJe+ErJeyRpjKjYbqjXf+FQLz2j3TFlkQZ2ShtV2xV/VQ5Futpf/63uX2YNTJVd5OccegEY9ij0RYNvB3yJmeH+aWN68LnD44cf46j5sqfzpU6VL4deJ4u9tnCkO7Nj/Dd0Kmmhc37ZHXFEfIJ/EEdovftYXgLcmGO3W4tGI8lo8ucs5uQYU/qacyUYprfMskcBTLD3eeupSl7cRs13K9tnpSlGoj6m4J2AjzziLNP3At7WgHJ8C5NZ5BTvTE3R6B4ZBefcHyizbGR3sgNUGytpXLzrnDjibj7Q6NzevjwvICOwVQ7NzlaYBD4uCucK8+HxsIQmGXkRAwK8oRJzPTD5fWfb3Fe5k78MmtvorGy0LfNhf9aPk00+XBPnbZxeVe7Xp5Y3qAqXkx2r4iVbW6f+IgblT0uk8Ll/2peiPji4nshBUxhx/CAejwbrkK9vzrX5vyCWZQANmbTWOY8xHfcyBJfKkrlpr9HyKYPjsL2rnNSMvsor7c5aNQzgbl3qzUZmWQXLmKLhUwu9NQnxXz8jR7Q0Gjok2clvFLZguSplfpRlrlR9v2u/R+mjk3T7uQs8dQ2MMBkofybWvMBy3xRb+A9lO3f9I43LFcJdxXsKsCl/MyE4P7VxA1jZ0qnvuaFh9mnyQG0/3XoSzwEms5Msj444kD51810=
    user: AgA7mf6n1gtkkWxJNeFgtwcLqTt+3FVvDm9JVVXraNk9gwWX+WZPdUXfGCypLkS4x2+/1T/t5aLJTgRyGOEiST1Ako4yflOYhToSF07wK1f8Q6G8PY4jDIunhsYSCPwhbV2Gm8ap+OmkMyrBlnuBbPiaWDze58RyhJ/Wq7ySf/tW1ak7+ZXdVRWfabUsh/L3ne1Pqa+UN0asEHOEzptcBMJ+DFdxOXiCPZgdf3QJGxWa8q2tqIH8HY72fZIdZDdmnM6hzpk7Y080PPb9CqkbhlbSTPvSuU4UF9E6osL1bzzldnb8aky+Yx3Dh4JL1bIbIhcE9dAw/Vcu0qUS7uGNHHnBl/oe5sYUNmFLEz6v9hPAUNZBrdTUNgXOlZ5JxgxYNnwuDsu5JZUo/IqDeb6ukbWNXDyXhP4uvTzVQd8oBNXED8LQxPafiniAdLPfwxL3CeimVOw2GzulIc5BXP6jilHynbKQA53+hSUhSt1rarnmQJMJycOHiFJT4Sx3lVPuUTiMtYMpMvXPqdG/csnnuvT6KFf9gOo1Ll0SgHUd6q902CkG5g33sQWgioJSKd2RHFLF+53QH+dDvTHQteX3vtn8uiHIcofJfjbVjDmH7EFQZiIDN/RgigL8XmyzAz7iHWEQUto6TYHekQzXo/tElC874Jclgy9rDWdKRJJJu268sdakNcdqm0r7TyaGcB8KHrzQQVhE2yhb6rej8OcTQ6O+UeIi5RehOKfL1GON
  template:
    metadata:
      name: grafana-admin-user
      namespace: monitoring
