
ingress:
  enabled: true
  ingressClassName: tailscale
  hosts:
    - grafana
  tls:
    - hosts:
      - grafana
      secretName: grafana-tls

admin:
  existingSecret: "grafana-admin-user"
  userKey: user
  passwordKey: password

persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path

dashboardProviders:
 dashboardproviders.yaml:
   apiVersion: 1
   providers:
   - name: 'default'
     orgId: 1
     folder: ''
     type: file
     disableDeletion: false
     editable: true
     options:
       path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes-dashboard:
      gnetId: 18283
      

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus:9090
        isDefault: true
        httpMethod: POST
