
ingress:
  enabled: true
  ingressClassName: tailscale
  hosts:
    - grafana
  tls:
    - hosts:
      - grafana
      secretName: grafana-tls

admin:
  existingSecret: "grafana-admin-user"
  userKey: user
  passwordKey: password

deploymentStrategy:
  type: Recreate # This is to avoid issues with the ReadWriteOnce access mode of the PVC

persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus:9090
        isDefault: true
        httpMethod: POST
